/* Automatically generated by version.sh, do not manually edit! */
#ifndef AVUTIL_FFVERSION_H
#define AVUTIL_FFVERSION_H
#define FFMPEG_VERSION "N-117671-g562524587e-20241027"
#endif /* AVUTIL_FFVERSION_H */
